
services:

  db_contenidos:
    image: postgres:17
    container_name: api_contenidos
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_database
    ports:
      - "5433:5432"
    volumes:
      - db_data_contenidos:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flask_network  # Conectar a la red compartida

  api_contenidos:
    build:
      context: . # Ruta a tu directorio de API de contenidos
    ports:
      - "8080:8080"
    depends_on:
      - db_contenidos
    networks:
      - flask_network  # Conectar a la misma red compartida

volumes:
  db_data_contenidos:

networks:
  flask_network: # Usando la red compartida
    external: true # Hace referencia a una red externa creada anteriorment

