version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: api_Contenidos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Contenidos
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
