from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.get_temporadas200_response_inner_episodios_inner import GetTemporadas200ResponseInnerEpisodiosInner
from openapi_server import util

from openapi_server.models.get_temporadas200_response_inner_episodios_inner import GetTemporadas200ResponseInnerEpisodiosInner  # noqa: E501

class GetTemporadas200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, numero_temporada=None, episodios=None):  # noqa: E501
        """GetTemporadas200ResponseInner - a model defined in OpenAPI

        :param numero_temporada: The numero_temporada of this GetTemporadas200ResponseInner.  # noqa: E501
        :type numero_temporada: int
        :param episodios: The episodios of this GetTemporadas200ResponseInner.  # noqa: E501
        :type episodios: List[GetTemporadas200ResponseInnerEpisodiosInner]
        """
        self.openapi_types = {
            'numero_temporada': int,
            'episodios': List[GetTemporadas200ResponseInnerEpisodiosInner]
        }

        self.attribute_map = {
            'numero_temporada': 'numeroTemporada',
            'episodios': 'episodios'
        }

        self._numero_temporada = numero_temporada
        self._episodios = episodios

    @classmethod
    def from_dict(cls, dikt) -> 'GetTemporadas200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getTemporadas_200_response_inner of this GetTemporadas200ResponseInner.  # noqa: E501
        :rtype: GetTemporadas200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def numero_temporada(self) -> int:
        """Gets the numero_temporada of this GetTemporadas200ResponseInner.

        Identifica el número del episodio en la temporada a la que se está accediendo  # noqa: E501

        :return: The numero_temporada of this GetTemporadas200ResponseInner.
        :rtype: int
        """
        return self._numero_temporada

    @numero_temporada.setter
    def numero_temporada(self, numero_temporada: int):
        """Sets the numero_temporada of this GetTemporadas200ResponseInner.

        Identifica el número del episodio en la temporada a la que se está accediendo  # noqa: E501

        :param numero_temporada: The numero_temporada of this GetTemporadas200ResponseInner.
        :type numero_temporada: int
        """

        self._numero_temporada = numero_temporada

    @property
    def episodios(self) -> List[GetTemporadas200ResponseInnerEpisodiosInner]:
        """Gets the episodios of this GetTemporadas200ResponseInner.

        Listado de episodios que conforman la temporada a la que se está accediendo en el array  # noqa: E501

        :return: The episodios of this GetTemporadas200ResponseInner.
        :rtype: List[GetTemporadas200ResponseInnerEpisodiosInner]
        """
        return self._episodios

    @episodios.setter
    def episodios(self, episodios: List[GetTemporadas200ResponseInnerEpisodiosInner]):
        """Sets the episodios of this GetTemporadas200ResponseInner.

        Listado de episodios que conforman la temporada a la que se está accediendo en el array  # noqa: E501

        :param episodios: The episodios of this GetTemporadas200ResponseInner.
        :type episodios: List[GetTemporadas200ResponseInnerEpisodiosInner]
        """

        self._episodios = episodios
